### PR TITLE
Preview iframe for surfaces

### PR DESCRIPTION
**Pull request by un-tone**
For #198.

### CODE REVIEW

**Comment by PatrykSzwer** [comment]
Looks neat! Just found out one thing.
When You create new, empty surface, and set it up same as e.g HolyGrailSurface (add same view URI and blending points) the preview is not showing anyway.

**Comment by un-tone** [comment]
@PatrykSzwer good catch! Thanks! I fixed it in the last commit, please check.

**Comment by PatrykSzwer** [comment]
Now It's working, good job! For me is actually good to go. 
I have only one concern. When You create new empty surface and just go into it, You will see in preview the default surface layer. I'm not if this wouldn't create some confusion in new users, who would thing e.g. that empty surface by default has topbar. But It's just my though, maybe we should ask @warpech, what do You thing about it?

**Comment by un-tone** [comment]
I think I should do something with it, e.g. show an empty Preview or just hide a preview iframe

**Comment by PatrykSzwer** [comment]
Ya, I'm thinking about maybe not empty but just some information, that there is nothing to show or something like this.

**Comment by un-tone** [comment]
@PatrykSzwer I added message for cases when a surface is not configured properly.

**Comment by PatrykSzwer** [comment]
Awesome! I would just change message to be something more precise, because "not configured properly" can mean anything. I would make it to something about invalid/empty View URI and/or no blending points to show. Something more about that.

**Comment by un-tone** [comment]
@PatrykSzwer fixed

**Comment by PatrykSzwer** [comment]
Now when I'm reading it: `Make sure that Surface view URI is correct and there are blending points created and refresh the page.` I think the `and refresh the page` part is redundant. WDYT? For me You can merge it after this last note.

**Pull request merged**
