### PR TITLE
194 routing at home page

### PR DESCRIPTION
**Pull request by PatrykSzwer**
For #194 .

This branch was based on branch from PR #196 and has to be proceed after #196 is merged.

### CODE REVIEW

**Comment by warpech** [comment]
Few things are still missing:

-  A column showing the name of the routed surface should be added to each of the routes.
- The link names are still not very clear. Pls change Global routing & Routing to All routes & Routes
- The page headers should have the same text as the buttons

**Comment by warpech** [comment]
The text in `README.md` needs to be aligned with the explanatory text in the Routes page.

**Comment by PatrykSzwer** [comment]
I was thinking about doing separate issue for Readme file and doing it separately just after this is merged. Can we do it that way or should we make those changes here too?

**Comment by warpech** [comment]
I found some problem:

1. Go to http://localhost:8080/WebsiteEditor/routing
2. Click on the "Create" button

### Expected

A new surface is created.

### Actual

There is an exception:

```
System.Exception: The surface with specified key is not found.
   at WebsiteEditor.ViewModels.RoutingPage.GetCurrentSurface() in c:\www\Website\src\WebsiteEditor\ViewModels\RoutingPage.json.cs:line 85
   at WebsiteEditor.ViewModels.RoutingPage.Handle(CreateTrigger action) in c:\www\Website\src\WebsiteEditor\ViewModels\RoutingPage.json.cs:line 65
   at WebsiteEditor.ViewModels.RoutingPage.JsonByExample.Schema.<>c.<.ctor>b__0_14(Json pup, Input`1 input)
   at Starcounter.Templates.Property`1.InvokeHandler(Json parent, Input`1 input) in C:\TeamCity\BuildAgent\work\sc-8255\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 267
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value) in C:\TeamCity\BuildAgent\work\sc-8255\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 289
   at Starcounter.XSON.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, String valueStr) in C:\TeamCity\BuildAgent\work\sc-8255\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 149
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-8255\Level1\src\Starcounter\TransactionManager.cs:line 551
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-8255\Level1\src\Starcounter\Transaction.cs:line 224
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-8255\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 67
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in C:\TeamCity\BuildAgent\work\sc-8255\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 38
   at Starcounter.XSON.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection, JsonPatchStatus previousStatus) in C:\TeamCity\BuildAgent\work\sc-8255\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 601
   at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-8255\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 495
   at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-8255\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 414
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-8255\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 69
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-8255\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\BuildAgent\work\sc-8255\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 793
HResult=-2146233088
```

**Comment by PatrykSzwer** [comment]
That actually exposes even bigger issue/case. Since we providing view of all routes, maybe we should also provide possibility to change surface of route there? Like It was before UI reorganizing?

**Comment by warpech** [comment]
Let's try not to implement all of the features in the world. The important part is to finish with #193.

Please just add the modal. If someone wants to change the routed surface, they can delete  a route and create a new one.

**Comment by PatrykSzwer** [comment]
I've added a small modal with surface selection.

**Comment by warpech** [comment]
10 tests are failing. Please fix.

**Comment by PatrykSzwer** [comment]
Seems like those fails are not related to changes in this PR, since partly same tests failed in second, not relevant PR https://github.com/StarcounterApps/Website/pull/212

**Comment by un-tone** [comment]
I'm investigating it. It seems there is a strange behavior of Blender.

**Comment by un-tone** [comment]
The reason why the tests does not pass: https://github.com/Starcounter/Home/issues/251

**Comment by un-tone** [comment]
I approved. We decided to add `Ignore` attribute to the failing tests since this PR changes does not really affect on this functionality and these tests.

**Comment by PatrykSzwer** [comment]
As we discussed with @un-tone, I've added ignored labels with proper comments above tests that are failing because of Starcounter/Home#251. After this issue will be fixed, @un-tone will remove tags in #215. 
Please do final verification since there was 2 merges and conflict fixes.

**Pull request merged**
