### PR TITLE
Fixed pinning rules mapping

### PR DESCRIPTION
**Pull request by un-tone**
Fixed https://github.com/StarcounterApps/Website/issues/140.
Added tests in according to https://github.com/StarcounterApps/Website/issues/126.

Doing tests have been found and fixed other issues related to pinning rules mapping/unmapping. Some of them appeared after changes in https://github.com/StarcounterApps/Website/issues/128.

I will appreciate if you spend some time for manual testing of the mapping/unmapping pinning rules, because this implementation has changed a lot and I could miss some important case.

### CODE REVIEW

**Comment by un-tone** [comment]
@PatrykSzwer could you check and maybe clear/update your dev env, because all tests pass on my local machine and in TeamCity https://teamcity.starcounter.org/viewLog.html?buildId=28392&buildTypeId=Apps_Website_Develop
image

**Comment by PatrykSzwer** [comment]
Hm, that's strange, because I already rebuild and pulled solution twice, and still getting same results. I'll investigate this further.

**Comment by PatrykSzwer** [comment]
For some reason, when I pulled Your last merge, It's working...

**Comment by un-tone** [comment]
There is another created issue for that https://github.com/StarcounterApps/Website/issues/139

**Comment by PatrykSzwer** [comment]
You're right! I Completely forgot about it. I'm still manually testing but Didn't find anything alarming yet.

**Comment by un-tone** [comment]
Great. Thanks!

**Pull request merged**
